---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Portada
- type: document
  path: data/es/homepage.yml
  label: Secciones portada
- type: heading
  label: Blog Post
- type: heading
  label: Project
- type: directory
  path: content/es/project
  label: Proyecto (es)
  create: all
  match: "**/*"
  templates:
  - project
- type: heading
  label: Productos
- type: directory
  path: content/es/service
  label: Producto (es)
  create: documents
  match: "*"
  templates:
  - service
- type: heading
  label: Team
- type: directory
  path: exampleSite/content/english/team
  label: Team (en)
  create: documents
  match: "*"
  templates:
  - team
- type: directory
  path: exampleSite/content/french/team
  label: Team (fr)
  create: documents
  match: "*"
  templates:
  - team
- type: heading
  label: P치ginas especiales
- type: directory
  path: exampleSite/content/english/about
  label: About (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/about
  label: About (fr)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/english/contact
  label: Contact (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/contact
  label: Contact (fr)
  create: none
  match: "*"
- type: directory
  path: content/es
  label: Todo el contenido en espa침ol
  create: all
  match: "**/*"
  new_doc_ext: ".md"
  templates:
  - service
  - project
  - team
  - post
  - new-page
- type: heading
  label: Data
- type: directory
  path: exampleSite/data/en
  label: Data (en)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/data/fr
  label: Data (fr)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: heading
  label: Traducciones
- type: document
  path: i18n/es.yaml
  label: Traducciones espa침ol
- type: heading
  label: Configuration
- type: document
  path: config.toml
  label: Configuraci칩n
  match: "**/*"
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
