---
new_page_extension: md
auto_deploy: false
admin_path: ".forestry"
webhook_url: 
sections:
- type: heading
  label: Portada
- type: document
  path: data/es/homepage.yml
  label: Secciones portada
- type: heading
  label: Productos
- type: directory
  path: content/es/service
  label: Producto (es)
  create: documents
  match: "*"
  templates:
  - service
- type: heading
  label: Proyectos
- type: directory
  path: content/es/project
  label: Proyecto (es)
  create: all
  match: "**/*"
  templates:
  - project
- type: heading
  label: Acerca de
- type: document
  path: data/es/about.yml
  label: Secciones de "acerca de"
- type: document
  path: content/es/about/_index.md
  label: Contenido "acerca de"
- type: heading
  label: Blog Post
- type: heading
  label: Team
- type: directory
  path: content/es/team
  label: Equipo (es)
  create: documents
  match: "*"
  templates:
  - team
- type: heading
  label: Páginas especiales
- type: directory
  path: content/es
  label: Todo el contenido en español
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - service
  - project
  - team
  - post
  - new-page
- type: document
  path: content/es/contact/_index.md
  label: Contacto (es)
- type: document
  path: content/es/search/_index.md
  label: Resultados de búsqueda
  match: "**/*"
- type: heading
  label: Traducciones
- type: document
  path: i18n/es.yaml
  label: Traducciones español
- type: heading
  label: Configuración
- type: document
  path: config.toml
  label: Configuración
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
